/**
 * @file test_transport_cmock.c
 * @brief CMock-based expectation tests of the transport contract.
 *
 * These tests verify the exact call sequences the engine makes against the
 * user-supplied transport callbacks — short-write retries, backpressure
 * delays, and the timeout-vs-I/O-error read contract — using mocks
 * generated by CMock from tests/support/transport.h.
 */

#include <string.h>

#include "unity.h"
#include "mock_transport.h"

#include "ec200.h"
#include "ec200_at.h"

static ec200_handle_t h;

/** Build a ready-to-use handle without going through the init probe. */
static void make_handle(void)
{
    memset(&h, 0, sizeof(h));
    h.write           = transport_write;
    h.read            = transport_read;
    h.delay_ms        = transport_delay;
    h._initialised    = true;
    h._last_cme_error = -1;
    h._last_cms_error = -1;
}

void setUp(void)
{
    mock_transport_Init();
    make_handle();
}

void tearDown(void)
{
    mock_transport_Verify();
    mock_transport_Destroy();
}

/* =========================================================================
 * Write path
 * ========================================================================= */

void test_write_all_retries_short_write(void)
{
    /* 8 bytes: transport accepts 3, then the remaining 5. */
    transport_write_ExpectAnyArgsAndReturn(3);
    transport_write_ExpectAnyArgsAndReturn(5);

    TEST_ASSERT_EQUAL_INT(EC200_OK,
        ec200_at_write_raw(&h, (const uint8_t *)"ABCDEFGH", 8));
}

void test_write_all_backpressure_delays_then_succeeds(void)
{
    /* A zero-byte write is backpressure: the engine must delay and retry. */
    transport_write_ExpectAnyArgsAndReturn(0);
    transport_delay_ExpectAnyArgs();
    transport_write_ExpectAnyArgsAndReturn(4);

    TEST_ASSERT_EQUAL_INT(EC200_OK,
        ec200_at_write_raw(&h, (const uint8_t *)"ABCD", 4));
}

void test_write_all_fatal_error(void)
{
    transport_write_ExpectAnyArgsAndReturn(-1);
    TEST_ASSERT_EQUAL_INT(EC200_ERR_IO,
        ec200_at_write_raw(&h, (const uint8_t *)"ABCD", 4));
}

void test_write_all_nonsense_return_is_io_error(void)
{
    /* A callback claiming to write MORE than requested is defective. */
    transport_write_ExpectAnyArgsAndReturn(99);
    TEST_ASSERT_EQUAL_INT(EC200_ERR_IO,
        ec200_at_write_raw(&h, (const uint8_t *)"ABCD", 4));
}

/* =========================================================================
 * Read path: timeout vs fatal error
 * ========================================================================= */

void test_read_raw_timeout_contract(void)
{
    /* timeout=100 → one 100 ms slice returning 0, then a final 0-budget
     * poll: both report "no data" → EC200_ERR_TIMEOUT (never ERR_IO). */
    transport_read_ExpectAnyArgsAndReturn(0);
    transport_read_ExpectAnyArgsAndReturn(0);

    uint8_t buf[4];
    uint16_t got = 0xFFFF;
    TEST_ASSERT_EQUAL_INT(EC200_ERR_TIMEOUT,
        ec200_at_read_raw(&h, buf, sizeof(buf), 100, &got));
    TEST_ASSERT_EQUAL_UINT16(0, got);
}

void test_read_raw_fatal_error_contract(void)
{
    transport_read_ExpectAnyArgsAndReturn(-1);

    uint8_t buf[4];
    uint16_t got = 0xFFFF;
    TEST_ASSERT_EQUAL_INT(EC200_ERR_IO,
        ec200_at_read_raw(&h, buf, sizeof(buf), 100, &got));
    TEST_ASSERT_EQUAL_UINT16(0, got);
}

/* =========================================================================
 * Command framing
 * ========================================================================= */

static int write_capture(const uint8_t *data, uint16_t len, void *user_ctx,
                         int num_calls)
{
    (void)user_ctx;
    (void)num_calls;
    TEST_ASSERT_EQUAL_UINT16(3, len);
    TEST_ASSERT_EQUAL_MEMORY("AT\r", data, 3);
    return (int)len;
}

void test_command_framed_with_cr(void)
{
    /* "AT" must go out as exactly "AT\r"; the response times out. */
    transport_write_Stub(write_capture);
    transport_read_IgnoreAndReturn(0);

    TEST_ASSERT_EQUAL_INT(EC200_ERR_TIMEOUT,
        ec200_at_send(&h, "AT", NULL, 0, 100));
}

void test_write_all_backpressure_exhausts_budget(void)
{
    /* Persistent backpressure: the engine must give up with a timeout. */
    transport_write_IgnoreAndReturn(0);
    transport_delay_Ignore();

    TEST_ASSERT_EQUAL_INT(EC200_ERR_TIMEOUT,
        ec200_at_write_raw(&h, (const uint8_t *)"ABCD", 4));
}

void test_read_exact_nonsense_return_is_io_error(void)
{
    /* A read callback claiming MORE bytes than requested is defective. */
    transport_read_IgnoreAndReturn(99);

    uint8_t buf[4];
    uint16_t got = 0xFFFF;
    TEST_ASSERT_EQUAL_INT(EC200_ERR_IO,
        ec200_at_read_exact(&h, buf, sizeof(buf), 100, &got));
}

/* ========================================================================= */

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_write_all_retries_short_write);
    RUN_TEST(test_write_all_backpressure_delays_then_succeeds);
    RUN_TEST(test_write_all_fatal_error);
    RUN_TEST(test_write_all_nonsense_return_is_io_error);
    RUN_TEST(test_read_raw_timeout_contract);
    RUN_TEST(test_read_raw_fatal_error_contract);
    RUN_TEST(test_command_framed_with_cr);
    RUN_TEST(test_write_all_backpressure_exhausts_budget);
    RUN_TEST(test_read_exact_nonsense_return_is_io_error);
    return UNITY_END();
}
